In [1]:
import numpy as np 
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

# Import Data

In [2]:
sales = pd.read_csv('/Users/galvanize/Desktop/final_project/summer-products-with-rating-and-performance_2020-08.csv')

In [3]:
unique_tag = pd.read_csv('/Users/galvanize/Desktop/final_project/unique-categories_tags.csv')

In [4]:
unique_cat = pd.read_csv('/Users/galvanize/Desktop/final_project/unique-categories.sorted-by-count.csv')

# Review data

In [5]:
sales.describe()
#sales.head()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
count,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1528.000000,1528.000000,1528.000000,1528.000000,...,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,473.0,1.573000e+03,1573.000000,1573.000000
mean,8.325372,23.288620,4339.005086,0.432931,3.820896,889.659250,442.263743,179.599476,134.549738,63.711387,...,0.012715,33.081373,2.345200,0.002543,40.456453,49.821360,1.0,2.649583e+04,4.032345,0.143675
std,3.932030,30.357863,9356.539302,0.495639,0.515374,1983.928834,980.203270,400.516231,311.690656,151.343933,...,0.112075,21.353137,1.024371,0.050379,20.301203,2.562799,0.0,7.847446e+04,0.204768,0.350871
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,6.000000,1.000000,1.0,0.000000e+00,2.333333,0.000000
25%,5.810000,7.000000,100.000000,0.000000,3.550000,24.000000,12.000000,5.000000,4.000000,2.000000,...,0.000000,6.000000,2.000000,0.000000,31.000000,50.000000,1.0,1.987000e+03,3.917353,0.000000
50%,8.000000,10.000000,1000.000000,0.000000,3.850000,150.000000,79.000000,31.500000,24.000000,11.000000,...,0.000000,50.000000,2.000000,0.000000,40.000000,50.000000,1.0,7.936000e+03,4.040650,0.000000
75%,11.000000,26.000000,5000.000000,1.000000,4.110000,855.000000,413.500000,168.250000,129.250000,62.000000,...,0.000000,50.000000,3.000000,0.000000,43.000000,50.000000,1.0,2.456400e+04,4.161797,0.000000
max,49.000000,252.000000,100000.000000,1.000000,5.000000,20744.000000,11548.000000,4152.000000,3658.000000,2003.000000,...,1.000000,50.000000,12.000000,1.000000,140.000000,50.000000,1.0,2.174765e+06,5.000000,1.000000

In [6]:
# see we have some nulls

In [7]:
sales.isnull().sum()[sales.isnull().sum() !=0]

rating_five_count              45
rating_four_count              45
rating_three_count             45
rating_two_count               45
rating_one_count               45
product_color                  41
product_variation_size_id      14
has_urgency_banner           1100
urgency_text                 1100
origin_country                 17
merchant_name                   4
merchant_info_subtitle          1
merchant_profile_picture     1347
dtype: int64

In [8]:
#For the ratings I don't want to get rid of the rows and the nulls are important information.  I will replace with 0
# rating features
sales['rating_five_count'].replace(np.nan, 0, inplace=True)
sales['rating_four_count'].replace(np.nan, 0, inplace=True)
sales['rating_three_count'].replace(np.nan, 0, inplace=True)
sales['rating_two_count'].replace(np.nan, 0, inplace=True)
sales['rating_one_count'].replace(np.nan, 0, inplace=True)

In [9]:
sales.describe()

,price,retail_price,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,rating_four_count,rating_three_count,rating_two_count,...,badge_fast_shipping,product_variation_inventory,shipping_option_price,shipping_is_express,countries_shipped_to,inventory_total,has_urgency_banner,merchant_rating_count,merchant_rating,merchant_has_profile_picture
count,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,...,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,1573.000000,473.0,1.573000e+03,1573.000000,1573.000000
mean,8.325372,23.288620,4339.005086,0.432931,3.820896,889.659250,429.611570,174.461538,130.700572,61.888748,...,0.012715,33.081373,2.345200,0.002543,40.456453,49.821360,1.0,2.649583e+04,4.032345,0.143675
std,3.932030,30.357863,9356.539302,0.495639,0.515374,1983.928834,968.882684,395.876511,308.015310,149.539900,...,0.112075,21.353137,1.024371,0.050379,20.301203,2.562799,0.0,7.847446e+04,0.204768,0.350871
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,0.000000,6.000000,1.000000,1.0,0.000000e+00,2.333333,0.000000
25%,5.810000,7.000000,100.000000,0.000000,3.550000,24.000000,10.000000,4.000000,3.000000,1.000000,...,0.000000,6.000000,2.000000,0.000000,31.000000,50.000000,1.0,1.987000e+03,3.917353,0.000000
50%,8.000000,10.000000,1000.000000,0.000000,3.850000,150.000000,72.000000,29.000000,22.000000,10.000000,...,0.000000,50.000000,2.000000,0.000000,40.000000,50.000000,1.0,7.936000e+03,4.040650,0.000000
75%,11.000000,26.000000,5000.000000,1.000000,4.110000,855.000000,394.000000,163.000000,121.000000,59.000000,...,0.000000,50.000000,3.000000,0.000000,43.000000,50.000000,1.0,2.456400e+04,4.161797,0.000000
max,49.000000,252.000000,100000.000000,1.000000,5.000000,20744.000000,11548.000000,4152.000000,3658.000000,2003.000000,...,1.000000,50.000000,12.000000,1.000000,140.000000,50.000000,1.0,2.174765e+06,5.000000,1.000000

In [10]:
# urgency banner
sales['has_urgency_banner'].replace(np.nan, 0, inplace=True)

In [11]:
# profile picture
sales['merchant_profile_picture'].replace(np.nan, 0, inplace=True)

In [12]:
sales.info()
#sales.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1573 entries, 0 to 1572
Data columns (total 43 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         1573 non-null   object
 1   title_orig                    1573 non-null   object
 2   price                         1573 non-null   float64
 3   retail_price                  1573 non-null   int64
 4   currency_buyer                1573 non-null   object
 5   units_sold                    1573 non-null   int64
 6   uses_ad_boosts                1573 non-null   int64
 7   rating                        1573 non-null   float64
 8   rating_count                  1573 non-null   int64
 9   rating_five_count             1573 non-null   float64
 10  rating_four_count             1573 non-null   float64
 11  rating_three_count            1573 non-null   float64
 12  rating_two_count              1573 non-null   float64
 13  rating_one_count              1573 non-null   float64
 14  badges_count                  1573 non-null   int64
 15  badge_local_product           1573 non-null   int64
 16  badge_product_quality         1573 non-null   int64
 17  badge_fast_shipping           1573 non-null   int64
 18  tags                          1573 non-null   object
 19  product_color                 1532 non-null   object
 20  product_variation_size_id     1559 non-null   object
 21  product_variation_inventory   1573 non-null   int64
 22  shipping_option_name          1573 non-null   object
 23  shipping_option_price         1573 non-null   int64
 24  shipping_is_express           1573 non-null   int64
 25  countries_shipped_to          1573 non-null   int64
 26  inventory_total               1573 non-null   int64
 27  has_urgency_banner            1573 non-null   float64
 28  urgency_text                  473 non-null    object
 29  origin_country                1556 non-null   object
 30  merchant_title                1573 non-null   object
 31  merchant_name                 1569 non-null   object
 32  merchant_info_subtitle        1572 non-null   object
 33  merchant_rating_count         1573 non-null   int64
 34  merchant_rating               1573 non-null   float64
 35  merchant_id                   1573 non-null   object
 36  merchant_has_profile_picture  1573 non-null   int64
 37  merchant_profile_picture      1573 non-null   object
 38  product_url                   1573 non-null   object
 39  product_picture               1573 non-null   object
 40  product_id                    1573 non-null   object
 41  theme                         1573 non-null   object
 42  crawl_month                   1573 non-null   object
dtypes: float64(9), int64(15), object(19)
memory usage: 528.6+ KB

In [13]:
sales.head(1)

,title,title_orig,price,retail_price,currency_buyer,units_sold,uses_ad_boosts,rating,rating_count,rating_five_count,...,merchant_rating_count,merchant_rating,merchant_id,merchant_has_profile_picture,merchant_profile_picture,product_url,product_picture,product_id,theme,crawl_month
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Pajamas Se...,16.0,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,0,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08

In [14]:
sales.dtypes[sales.dtypes == 'int']

retail_price                    int64
units_sold                      int64
uses_ad_boosts                  int64
rating_count                    int64
badges_count                    int64
badge_local_product             int64
badge_product_quality           int64
badge_fast_shipping             int64
product_variation_inventory     int64
shipping_option_price           int64
shipping_is_express             int64
countries_shipped_to            int64
inventory_total                 int64
merchant_rating_count           int64
merchant_has_profile_picture    int64
dtype: object

In [15]:
sales.dtypes[sales.dtypes == 'object']

title                        object
title_orig                   object
currency_buyer               object
tags                         object
product_color                object
product_variation_size_id    object
shipping_option_name         object
urgency_text                 object
origin_country               object
merchant_title               object
merchant_name                object
merchant_info_subtitle       object
merchant_id                  object
merchant_profile_picture     object
product_url                  object
product_picture              object
product_id                   object
theme                        object
crawl_month                  object
dtype: object

In [16]:
sales.dtypes[sales.dtypes == 'float']

price                 float64
rating                float64
rating_five_count     float64
rating_four_count     float64
rating_three_count    float64
rating_two_count      float64
rating_one_count      float64
has_urgency_banner    float64
merchant_rating       float64
dtype: object

In [17]:
sales.isnull().sum()[sales.isnull().sum() !=0]

product_color                  41
product_variation_size_id      14
urgency_text                 1100
origin_country                 17
merchant_name                   4
merchant_info_subtitle          1
dtype: int64

In [18]:
sales.urgency_text.unique()

array(['QuantitÃ© limitÃ©e !', nan, 'RÃ©duction sur les achats en gros'],
      dtype=object)

In [19]:
sales['urgency_text'].value_counts()

QuantitÃ© limitÃ©e !                  472
RÃ©duction sur les achats en gros      1
Name: urgency_text, dtype: int64

In [20]:
#Change the wording to english for urgency text
sales['urgency_text'] = sales['urgency_text'].replace({'QuantitÃ© limitÃ©e !':'Limited_quantity!', 'RÃ©duction sur les achats en gros':'Discount_on_wholesale_purchases'})

In [21]:
sales['urgency_text'].value_counts()

Limited_quantity!                  472
Discount_on_wholesale_purchases      1
Name: urgency_text, dtype: int64

In [22]:
# create new columns for gross

In [23]:
sales['gross'] = sales['price']*sales['units_sold']

In [ ]:
sales.info()

In [ ]:
sales['product_color'].value_counts()